"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import jsQR from "jsqr";

type AdminView = "overview" | "calendar" | "activity" | "customers" | "loyalty" | "services" | "staff" | "settings";

type AdminCustomer = { id: string; first_name: string | null; last_name: string | null; member_code: string; created_at: string };
type AdminService = { id: string; name: string; description: string | null; category: string; is_bookable: boolean; active: boolean; display_order: number };
type AdminReward = { id: string; visit_number: number; name: string; description: string | null; terms: string | null; valid_days: number | null; is_free_product: boolean; active: boolean };
type AdminAppointment = { id: string; user_id: string; service_name: string; scheduled_start: string; status: string };
type AdminVisit = { id: string; account_id: string; occurred_at: string; user_id: string };
type AdminData = { customers: AdminCustomer[]; services: AdminService[]; rewards: AdminReward[]; appointments: AdminAppointment[]; visits?: AdminVisit[]; loyaltyMembers: number; rewardsIssued: number };

const nav = ([
  { id: "calendar", label: "Calendar", icon: "▣" },
  { id: "activity", label: "Activity Logs", icon: "◷" },
  { id: "overview", label: "Overview", icon: "▦" },
  { id: "customers", label: "Customers", icon: "♙" },
  { id: "loyalty", label: "Loyalty & Offers", icon: "◇" },
  { id: "services", label: "Products & Services", icon: "◉" },
  { id: "staff", label: "Staff", icon: "♧" },
  { id: "settings", label: "Spa Settings", icon: "⚙" },
] as { id: AdminView; label: string; icon: string }[]).filter(item => ["overview", "customers", "calendar", "activity", "settings"].includes(item.id)).sort((a, b) => ["overview", "customers", "calendar", "activity", "settings"].indexOf(a.id) - ["overview", "customers", "calendar", "activity", "settings"].indexOf(b.id)).map(item => item.id === "activity" ? { ...item, label: "Logs" } : item);

function LegacyAdminSidebar({ view, setView }: { view: AdminView; setView: (view: AdminView) => void }) {
  const router = useRouter();
  async function logout() { await createClient().auth.signOut(); router.replace("/login"); router.refresh(); }
  return <aside className="admin-sidebar"><div className="admin-brand"><Image src="/prime-iv-logo.png" alt="Prime IV Hydration & Wellness" width={206} height={165} priority /></div><div className="admin-spa-card"><div><span className="sample-badge">Sample spa</span><strong>Prime IV Spa 1</strong><small>spa-1</small></div><button aria-label="Change spa">⌄</button></div><p className="admin-nav-label">Workspace</p><nav aria-label="Admin modules">{nav.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><i>{item.icon}</i><span>{item.label}</span></button>)}</nav><div className="admin-sidebar-bottom"><Link href="/">View customer portal ↗</Link><button className="admin-logout" onClick={logout}>↪ Log out</button><small>Powered by PatientConvert</small></div></aside>;
}

function createSignupWidgetSnippet(signupUrl: string) {
  const safeUrl = signupUrl.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<!-- Prime IV Loyalty signup widget -->
<section id="pc-piv-loyalty-widget" class="pc-piv-loyalty-widget" data-signup-url="${safeUrl}" aria-labelledby="pc-piv-loyalty-widget-title">
  <div class="pc-piv-loyalty-widget__glow" aria-hidden="true"></div>
  <div class="pc-piv-loyalty-widget__content">
    <p class="pc-piv-loyalty-widget__eyebrow">LOYALTY &amp; WELLNESS</p>
    <h2 id="pc-piv-loyalty-widget-title" class="pc-piv-loyalty-widget__title">Every visit brings your next reward closer.</h2>
    <p class="pc-piv-loyalty-widget__intro">Join your spa's loyalty portal and keep your wellness journey in one convenient place.</p>
    <div class="pc-piv-loyalty-widget__card" aria-label="Five-visit loyalty reward preview">
      <div class="pc-piv-loyalty-widget__card-head"><div><span>YOUR WELLNESS JOURNEY</span><strong>Five visits. More to look forward to.</strong></div><b>LOYALTY REWARDS</b></div>
      <div class="pc-piv-loyalty-widget__punches">
        <div><i>1</i><strong>Welcome visit</strong><small>Start your journey</small></div>
        <div><i>2</i><strong>$25 credit</strong><small>Your next reward</small></div>
        <div><i>3</i><strong>IV additive</strong><small>Complimentary</small></div>
        <div><i>4</i><strong>NAD shot</strong><small>Complimentary</small></div>
        <div><i>5</i><strong>IV drip</strong><small>Complimentary</small></div>
      </div>
      <p class="pc-piv-loyalty-widget__disclaimer">Reward details are set by your spa and may vary.</p>
    </div>
    <ul class="pc-piv-loyalty-widget__benefits">
      <li><span aria-hidden="true">✓</span><strong>Earn visit rewards</strong><small>Track milestones and see what reward is coming next.</small></li>
      <li><span aria-hidden="true">✓</span><strong>Use your member QR</strong><small>Show your secure QR at check-in for verified visits.</small></li>
      <li><span aria-hidden="true">✓</span><strong>Self-book with ease</strong><small>Choose a service and schedule your next spa visit.</small></li>
    </ul>
    <a id="pc-piv-loyalty-widget-cta" class="pc-piv-loyalty-widget__cta" href="${safeUrl}" target="_blank" rel="noopener noreferrer">Create my loyalty account <span aria-hidden="true">→</span></a>
    <p class="pc-piv-loyalty-widget__note">Free to join. Your account is connected only to this spa.</p>
  </div>
</section>
<style>
#pc-piv-loyalty-widget.pc-piv-loyalty-widget{--pc-piv-navy:#06457f;--pc-piv-blue:#086caf;--pc-piv-sky:#35a9df;--pc-piv-pale:#edf7fb;position:relative;box-sizing:border-box;width:100%;max-width:1080px;margin:24px auto;padding:clamp(24px,5vw,54px);overflow:hidden;border:1px solid #cfe2eb;border-radius:24px;background:linear-gradient(135deg,#f8fcfe 0%,#edf7fb 100%);box-shadow:0 18px 50px rgba(6,69,127,.10);font-family:Arial,Helvetica,sans-serif;color:#15364f}
#pc-piv-loyalty-widget *{box-sizing:border-box}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__glow{position:absolute;width:330px;height:330px;right:-140px;top:-170px;border:55px solid rgba(53,169,223,.10);border-radius:50%;pointer-events:none}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__content{position:relative;z-index:1;max-width:850px;margin:auto;text-align:center}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__eyebrow{margin:0 0 10px;color:var(--pc-piv-blue);font-size:12px;font-weight:800;letter-spacing:.16em}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__title{margin:0;color:var(--pc-piv-navy);font-size:clamp(28px,4.5vw,48px);line-height:1.08;letter-spacing:-.035em}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__intro{max-width:650px;margin:16px auto 28px;color:#587284;font-size:clamp(15px,2vw,18px);line-height:1.6}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card{margin:0 0 22px;padding:22px;border-radius:19px;background:linear-gradient(135deg,var(--pc-piv-navy),var(--pc-piv-blue));box-shadow:0 15px 35px rgba(6,69,127,.20);color:#fff;text-align:left}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding-bottom:18px;border-bottom:1px solid rgba(255,255,255,.22)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head>div{display:flex;flex-direction:column;gap:5px}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head span,#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head b{color:#a9dcf2;font-size:10px;letter-spacing:.13em}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head strong{font-size:clamp(18px,2.5vw,25px)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches{position:relative;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;padding-top:22px}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches:before{content:"";position:absolute;left:8%;right:8%;top:42px;border-top:2px dashed rgba(255,255,255,.28)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches>div{position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;text-align:center}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches i{width:42px;height:42px;display:grid;place-items:center;margin-bottom:10px;border:2px solid #a9dcf2;border-radius:50%;background:#fff;color:var(--pc-piv-blue);font-style:normal;font-weight:800;box-shadow:0 0 0 5px rgba(255,255,255,.10)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches strong{font-size:12px;line-height:1.25}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches small{margin-top:3px;color:#b8dff0;font-size:10px}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__disclaimer{margin:16px 0 0;color:rgba(255,255,255,.58);font-size:10px;text-align:center}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:0 0 28px;padding:0;list-style:none;text-align:left}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits li{display:grid;grid-template-columns:30px 1fr;gap:3px 10px;padding:18px;border:1px solid #d8e8ef;border-radius:15px;background:rgba(255,255,255,.88)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits li>span{grid-row:1/3;width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:var(--pc-piv-blue);color:#fff;font-weight:800}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits strong{color:var(--pc-piv-navy);font-size:15px}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits small{color:#67808f;font-size:13px;line-height:1.45}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__cta{display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:50px;padding:13px 22px;border-radius:11px;background:linear-gradient(135deg,var(--pc-piv-navy),var(--pc-piv-blue));box-shadow:0 10px 24px rgba(8,108,175,.22);color:#fff;text-decoration:none;font-size:16px;font-weight:800;transition:transform .2s ease,box-shadow .2s ease}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__cta:hover{transform:translateY(-2px);box-shadow:0 14px 28px rgba(8,108,175,.28)}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__cta:focus-visible{outline:3px solid var(--pc-piv-sky);outline-offset:3px}
#pc-piv-loyalty-widget .pc-piv-loyalty-widget__note{margin:12px 0 0;color:#78909e;font-size:12px}
@media(max-width:760px){#pc-piv-loyalty-widget.pc-piv-loyalty-widget{margin:14px auto;padding:26px 18px;border-radius:18px}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card{padding:18px 14px}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head{display:block}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__card-head>b{display:block;margin-top:9px}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches{grid-template-columns:repeat(5,78px);overflow-x:auto;padding:22px 4px 8px;scrollbar-width:thin}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__punches:before{display:none}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__benefits{grid-template-columns:1fr}#pc-piv-loyalty-widget .pc-piv-loyalty-widget__cta{width:100%}}
@media(prefers-reduced-motion:reduce){#pc-piv-loyalty-widget .pc-piv-loyalty-widget__cta{transition:none}}
</style>
<script>
(function(){var widget=document.getElementById('pc-piv-loyalty-widget');var cta=document.getElementById('pc-piv-loyalty-widget-cta');if(!widget||!cta)return;var url=widget.getAttribute('data-signup-url');if(url){cta.setAttribute('href',url);}cta.addEventListener('click',function(){widget.setAttribute('data-cta-clicked','true');});})();
</script>`;
}

function AdminSidebar({ view, setView }: { view: AdminView; setView: (view: AdminView) => void }) {
  const router = useRouter(); const [copyState, setCopyState] = useState("Copy signup link");
  async function logout() { await createClient().auth.signOut(); router.replace("/login"); router.refresh(); }
  async function copySignupLink() { try { setCopyState("Preparing link..."); const response = await fetch("/api/admin/signup-link", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Signup link unavailable."); try { await navigator.clipboard.writeText(result.url); } catch { const input = document.createElement("textarea"); input.value = result.url; input.style.position = "fixed"; input.style.opacity = "0"; document.body.appendChild(input); input.select(); const copied = document.execCommand("copy"); input.remove(); if (!copied) throw new Error("Your browser blocked clipboard access."); } setCopyState("Copied!"); setTimeout(() => setCopyState("Copy signup link"), 1800); } catch (error) { const message = error instanceof Error ? error.message : "Signup link unavailable."; setCopyState("Could not copy"); window.alert(message); setTimeout(() => setCopyState("Copy signup link"), 2500); } }
  useEffect(() => { const bottom = document.querySelector(".admin-sidebar-bottom"); const copyButton = bottom?.querySelector(".copy-signup-link"); if (!bottom || !copyButton || bottom.querySelector(".get-signup-snippet")) return; const button = document.createElement("button"); button.className = "copy-signup-link get-signup-snippet"; button.textContent = "</> Get signup snippet"; button.onclick = async () => { try { button.textContent = "Preparing snippet..."; const response = await fetch("/api/admin/signup-link", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Signup link unavailable."); const snippet = createSignupWidgetSnippet(result.url); await navigator.clipboard.writeText(snippet); button.textContent = "Widget copied!"; setTimeout(() => { button.textContent = "</> Get signup snippet"; }, 1800); } catch (error) { button.textContent = "Could not copy snippet"; window.alert(error instanceof Error ? error.message : "Unable to create signup snippet."); setTimeout(() => { button.textContent = "</> Get signup snippet"; }, 2500); } }; bottom.insertBefore(button, copyButton); return () => button.remove(); }, []);
  return <aside className="admin-sidebar"><div className="admin-brand"><Image src="/prime-iv-logo.png" alt="Prime IV Hydration & Wellness" width={206} height={165} priority /></div><div className="admin-spa-card"><div><span className="sample-badge">Sample spa</span><strong>Prime IV Spa 1</strong><small>spa-1</small></div><button aria-label="Change spa">⌄</button></div><p className="admin-nav-label">Workspace</p><nav aria-label="Admin modules">{nav.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><i>{item.icon}</i><span>{item.label}</span></button>)}</nav><div className="admin-sidebar-bottom"><button className="copy-signup-link" onClick={copySignupLink}>⧉ {copyState}</button><Link href="/">View customer portal ↗</Link><button className="admin-logout" onClick={logout}>↪ Log out</button><small>Powered by PatientConvert</small></div></aside>;
}

function AdminHeader({ title }: { title: string }) {
  const [query, setQuery] = useState("");
  function search(value: string) { setQuery(value); window.dispatchEvent(new CustomEvent("admin:customer-search", { detail: value })); }
  return <header className="admin-header"><div><span>Prime IV Spa 1</span><strong>{title}</strong></div><div className="admin-header-actions"><label className="admin-search">⌕ <input aria-label="Search customers" value={query} onChange={event => search(event.target.value)} placeholder="Search customers..." /><kbd>⌘ K</kbd></label><button className="admin-notification" aria-label="Notifications">○<i /></button><button className="admin-profile"><span>AD</span><div><strong>Admin</strong><small>Spa administrator</small></div><b>⌄</b></button></div></header>;
}

function LegacyOverview({ data, openCustomers }: { data: AdminData; openCustomers: () => void }) {
  const bookable = data.services.filter(service => service.is_bookable).length;
  const rewards = data.services.length - bookable;
  return <><div className="admin-title"><div><p>Sample spa workspace</p><h1>Good morning, Admin.</h1><span>Live information for Prime IV Spa 1.</span></div><button className="admin-primary" onClick={openCustomers}>+ Add customer</button></div><section className="admin-metrics"><article><span className="metric-icon blue">♙</span><div><small>Total customers</small><strong>{data.customers.length}</strong><p><b>Live from Supabase</b></p></div></article><article><span className="metric-icon cyan">◇</span><div><small>Loyalty members</small><strong>{data.loyaltyMembers}</strong><p>Active Spa 1 accounts</p></div></article><article><span className="metric-icon pink">◇</span><div><small>Rewards issued</small><strong>{data.rewardsIssued}</strong><p>Current award records</p></div></article><article><span className="metric-icon green">◉</span><div><small>Active products</small><strong>{data.services.length}</strong><p><b>{bookable} bookable</b> · {rewards} rewards</p></div></article></section><div className="admin-dashboard-grid"><section className="admin-panel"><div className="panel-heading"><div><p>Membership</p><h2>Recent customers</h2></div><button onClick={openCustomers}>View all →</button></div><div className="appointment-list">{data.customers.map(customer => { const name = [customer.first_name, customer.last_name].filter(Boolean).join(" ") || "Unnamed customer"; return <article key={customer.id}><time>{new Date(customer.created_at).toLocaleDateString()}</time><span className="customer-initial">{name.split(" ").map(part => part[0]).join("").slice(0,2)}</span><div><strong>{name}</strong><small>{customer.member_code}</small></div><em className="confirmed">Active</em></article>; })}</div></section><section className="admin-panel quick-panel"><div className="panel-heading"><div><p>Shortcuts</p><h2>Quick actions</h2></div></div><button onClick={openCustomers}><span>♙</span><div><strong>Register a customer</strong><small>Create a spa-linked account</small></div>→</button><button><span>▣</span><div><strong>Scan member QR</strong><small>Find loyalty membership</small></div>→</button><button><span>◇</span><div><strong>Manage rewards</strong><small>Edit visit milestones</small></div>→</button></section></div></>;
}

function QrScanner({ onClose }: { onClose: () => void }) {
  const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [scanning, setScanning] = useState(false); const [saving, setSaving] = useState(false);
  async function record(qrToken: string) { if (saving || !qrToken.trim()) return; setSaving(true); setMessage(""); const response = await fetch("/api/admin/visits", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ qrToken: qrToken.trim() }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "Unable to record this visit."); setSaving(false); return; } setMessage(result.completedAppointmentId ? `Visit ${result.visit.visit_number} recorded and self-booked appointment completed for ${result.member.first_name || "member"}.` : `Visit ${result.visit.visit_number} recorded for ${result.member.first_name || "member"}.`); setSaving(false); setTimeout(() => window.location.reload(), 1100); }
  useEffect(() => { if (!scanning) return; let stream: MediaStream | null = null; let frame = 0; let stopped = false; const video = document.querySelector<HTMLVideoElement>("#member-qr-camera"); const canvas = document.createElement("canvas"); const context = canvas.getContext("2d", { willReadFrequently: true }); (async () => { try { stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); if (!video || !context) return; video.srcObject = stream; await video.play(); const check = async () => { if (stopped || !video || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) { frame = requestAnimationFrame(check); return; } const width = video.videoWidth; const height = video.videoHeight; if (width && height) { canvas.width = width; canvas.height = height; context.drawImage(video, 0, 0, width, height); const image = context.getImageData(0, 0, width, height); const code = jsQR(image.data, width, height, { inversionAttempts: "attemptBoth" }); if (code?.data) { stopped = true; stream?.getTracks().forEach(track => track.stop()); setToken(code.data); await record(code.data); return; } } frame = requestAnimationFrame(check); }; check(); } catch { setMessage("Camera access was unavailable. Allow camera permission or enter the member code below."); } })(); return () => { stopped = true; cancelAnimationFrame(frame); stream?.getTracks().forEach(track => track.stop()); }; }, [scanning]);
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="qr-scanner-modal" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}><button className="close-button" onClick={onClose}>×</button><p className="kicker">Customer check-in</p><h2>Scan member QR</h2><p>Validate the customer and add one verified spa visit.</p>{scanning ? <video id="member-qr-camera" muted playsInline /> : <button className="scanner-start" onClick={() => setScanning(true)}>Open camera</button>}<div className="scanner-divider"><span>or enter member code</span></div><div className="scanner-manual"><input value={token} onChange={event => setToken(event.target.value)} placeholder="PIV-XXXXXXXX or QR token" /><button disabled={saving || !token.trim()} onClick={() => record(token)}>{saving ? "Checking…" : "Record visit"}</button></div>{message && <p className={message.startsWith("Visit") ? "scanner-success" : "login-error"}>{message}</p>}</section></div>;
}

function OverviewBase({ data: sourceData }: { data: AdminData; openCustomers?: () => void }) {
  const data = { ...sourceData, customers: sourceData.customers.map(customer => ({ ...customer, first_name: [customer.first_name, customer.last_name].filter(Boolean).join(" "), last_name: null })) };
  const [range, setRange] = useState("today"); const [showScanner, setShowScanner] = useState(false);
  const today = new Date(); const start = new Date(today.getFullYear(), today.getMonth(), today.getDate()); const end = new Date(start); end.setDate(end.getDate() + 1);
  const scheduledToday = data.appointments.filter(item => { const date = new Date(item.scheduled_start); return date >= start && date < end && !["cancelled", "no_show"].includes(item.status); });
  const cutoff = range === "today" ? start : range === "7" ? new Date(Date.now() - 7 * 86400000) : range === "30" ? new Date(Date.now() - 30 * 86400000) : new Date(0);
  const visits = (data.visits ?? []).filter(item => new Date(item.occurred_at) >= cutoff);
  return <><div className="admin-title"><div><p>Sample spa workspace</p><h1>Good morning, Admin.</h1><span>Live information for Prime IV Spa 1.</span></div><div className="overview-actions"><select value={range} onChange={event => setRange(event.target.value)} aria-label="Overview date filter"><option value="today">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="all">All time</option></select><button className="admin-primary" onClick={() => setShowScanner(true)}>Scan QR</button></div></div><section className="admin-metrics"><article><span className="metric-icon blue">C</span><div><small>Total customers</small><strong>{data.customers.length}</strong><p>Active spa customers</p></div></article><article><span className="metric-icon cyan">V</span><div><small>Verified visits</small><strong>{visits.length}</strong><p>For selected period</p></div></article><article><span className="metric-icon pink">R</span><div><small>Rewards issued</small><strong>{data.rewardsIssued}</strong><p>Current award records</p></div></article><article><span className="metric-icon green">T</span><div><small>Scheduled today</small><strong>{scheduledToday.length}</strong><p>Requested or confirmed</p></div></article></section><div className="admin-dashboard-grid"><section className="admin-panel"><div className="panel-heading"><div><p>Today</p><h2>Scheduled appointments</h2></div></div><div className="appointment-list">{scheduledToday.length ? scheduledToday.slice(0,5).map(item => <article key={item.id}><time>{new Date(item.scheduled_start).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time><span className="customer-initial">{item.service_name.slice(0,2).toUpperCase()}</span><div><strong>{item.service_name}</strong><small>{data.customers.find(customer => customer.id === item.user_id)?.first_name || "Customer"}</small></div><em className={item.status}>{item.status}</em></article>) : <p className="empty-log">Nothing scheduled today.</p>}</div></section><section className="admin-panel quick-panel"><div className="panel-heading"><div><p>Check-in</p><h2>Record a spa visit</h2></div></div><div className="scan-qr-prompt"><span>▦</span><strong>Scan a customer QR</strong><p>A valid QR adds exactly one verified visit and updates loyalty progress.</p><button className="admin-primary" onClick={() => setShowScanner(true)}>Open scanner</button></div></section></div>{showScanner && <QrScanner onClose={() => setShowScanner(false)} />}</>;
}

function Overview({ data }: { data: AdminData; openCustomers?: () => void }) {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 86400000);
  const newCustomers = data.customers.filter(customer => new Date(customer.created_at) >= thirtyDaysAgo).length;
  const completedAppointments = data.appointments.filter(item => item.status === "completed").length;
  const completionRate = data.appointments.length ? Math.round(completedAppointments / data.appointments.length * 100) : 0;
  const visitors = new Set((data.visits ?? []).map(visit => visit.user_id));
  const loyaltyReach = data.customers.length ? Math.round(visitors.size / data.customers.length * 100) : 0;
  const startToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const visitDays = Array.from({ length: 7 }, (_, index) => { const date = new Date(startToday); date.setDate(startToday.getDate() - (6 - index)); const next = new Date(date); next.setDate(date.getDate() + 1); return { label: date.toLocaleDateString([], { weekday: "short" }), count: (data.visits ?? []).filter(visit => { const occurred = new Date(visit.occurred_at); return occurred >= date && occurred < next; }).length }; });
  const maxDailyVisits = Math.max(1, ...visitDays.map(day => day.count));
  return <div className="overview-page"><OverviewBase data={data} /><section className="analytics-grid" aria-label="Spa analytics">
    <article className="analytics-card"><div><small>Customer growth</small><strong>+{newCustomers}</strong></div><span className="analytics-icon blue">↗</span><p>New customers in the last 30 days</p></article>
    <article className="analytics-card trend-card"><div><small>Visit trend</small><strong>{visitDays.reduce((sum, day) => sum + day.count, 0)}</strong></div><div className="mini-bars">{visitDays.map(day => <span key={day.label} title={`${day.label}: ${day.count} visits`}><i style={{ height: `${Math.max(8, day.count / maxDailyVisits * 100)}%` }} /><small>{day.label.slice(0, 1)}</small></span>)}</div><p>Verified visits over the last seven days</p></article>
    <article className="analytics-card"><div><small>Appointment completion</small><strong>{completionRate}%</strong></div><span className="analytics-icon green">✓</span><div className="analytics-progress"><i style={{ width: `${completionRate}%` }} /></div><p>{completedAppointments} of {data.appointments.length} appointments completed</p></article>
    <article className="analytics-card"><div><small>Loyalty engagement</small><strong>{loyaltyReach}%</strong></div><span className="analytics-icon pink">◇</span><div className="analytics-progress loyalty"><i style={{ width: `${loyaltyReach}%` }} /></div><p>{visitors.size} customers have a verified visit</p></article>
  </section></div>;
}

function LoyaltyEditor({ rewards, onUpdated }: { rewards: AdminReward[]; onUpdated: (reward: AdminReward) => void }) {
  const [editing, setEditing] = useState<AdminReward | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  async function save() { if (!editing) return; setSaving(true); setError(""); const response = await fetch(`/api/admin/rewards/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to save reward."); else { onUpdated(result.reward); setEditing(null); } setSaving(false); }
  return <><div className="admin-title"><div><p>Management</p><h1>Loyalty &amp; Offers</h1><span>Configure the five-visit journey for this spa.</span></div><span className="default-program-badge">Default · 5 visits</span></div><section className="admin-panel loyalty-editor"><div className="loyalty-editor-head"><div><p className="kicker">Your journey</p><h2>Five visits. More to look forward to.</h2></div><p>Each spa starts with this program and can customize its rewards.</p></div><div className="admin-milestones">{rewards.map((reward, index) => <article key={reward.id}><div className="admin-milestone-line"><span>{reward.visit_number}</span>{index < rewards.length - 1 && <i />}</div><div><small>Visit {reward.visit_number}</small><strong>{reward.name}</strong><p>{reward.description}</p><em>{reward.active ? "Active" : "Inactive"}</em><button onClick={() => setEditing({ ...reward })}>Edit reward</button></div></article>)}</div></section>{editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><section className="reward-edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-reward-title" onMouseDown={event => event.stopPropagation()}><div className="privacy-modal-header"><div><p className="kicker">Visit {editing.visit_number}</p><h2 id="edit-reward-title">Edit reward</h2></div><button className="close-button" onClick={() => setEditing(null)} aria-label="Close">×</button></div><div className="reward-edit-body"><label><span>Reward name</span><input value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><label><span>Description</span><textarea value={editing.description ?? ""} onChange={event => setEditing({ ...editing, description: event.target.value })} /></label><label><span>Terms <small>Optional</small></span><textarea value={editing.terms ?? ""} onChange={event => setEditing({ ...editing, terms: event.target.value })} /></label><label><span>Expires after <small>Optional days</small></span><input type="number" min="1" value={editing.valid_days ?? ""} onChange={event => setEditing({ ...editing, valid_days: event.target.value ? Number(event.target.value) : null })} /></label><label className="toggle-row"><input type="checkbox" checked={editing.active} onChange={event => setEditing({ ...editing, active: event.target.checked })} /><span>Reward is active</span></label>{error && <p className="login-error">{error}</p>}</div><div className="privacy-modal-footer"><button className="admin-soft" onClick={() => setEditing(null)}>Cancel</button><button className="admin-primary" disabled={saving || !editing.name.trim()} onClick={save}>{saving ? "Saving…" : "Save reward"}</button></div></section></div>}</>;
}

function ServicesEditor({ services, onUpdated, onCreated, onDeleted }: { services: AdminService[]; onUpdated: (service: AdminService) => void; onCreated: (service: AdminService) => void; onDeleted: (id: string) => void }) {
  const empty = { name: "", description: "", category: "service", is_bookable: true };
  const [editing, setEditing] = useState<AdminService | null>(null);
  const [creating, setCreating] = useState(false);
  const [draft, setDraft] = useState(empty);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  async function save() { if (!editing) return; setSaving(true); setError(""); const response = await fetch(`/api/admin/services/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to save service."); else { onUpdated(result.service); setEditing(null); } setSaving(false); }
  async function add() { setSaving(true); setError(""); const response = await fetch("/api/admin/services", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to add product or service."); else { onCreated(result.service); setDraft(empty); setCreating(false); } setSaving(false); }
  async function remove(service: AdminService) { if (!window.confirm(`Delete “${service.name}”? It will be removed from this catalog and customer scheduling.`)) return; setSaving(true); const response = await fetch(`/api/admin/services/${service.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) window.alert(result.error ?? "Unable to delete this item."); else onDeleted(service.id); setSaving(false); }
  return <>
    <div className="admin-title"><div><p>Catalog</p><h1>Products &amp; Services</h1><span>Bookable services appear in Schedule My Visit.</span></div><button className="admin-primary" onClick={() => { setError(""); setCreating(true); }}>+ Add product or service</button></div>
    <section className="admin-panel table-panel"><div className="table-tools"><div><button className="active">All {services.length}</button><button>Bookable {services.filter(item => item.is_bookable).length}</button><button>Rewards {services.filter(item => !item.is_bookable).length}</button></div></div><table><thead><tr><th>Name</th><th>Category</th><th>Usage</th><th>Status</th><th>Actions</th></tr></thead><tbody>{services.map(service => <tr key={service.id}><td><span className="service-mark">●</span><strong>{service.name}</strong></td><td>{service.category.replaceAll("_", " ")}</td><td>{service.is_bookable ? "Schedule option" : "Reward only"}</td><td><em className="active-status">● {service.active ? "Active" : "Inactive"}</em></td><td className="service-actions"><button className="service-edit-button" onClick={() => { setError(""); setEditing({ ...service }); }}>Edit</button><button className="service-delete-button" disabled={saving} onClick={() => remove(service)}>Delete</button></td></tr>)}</tbody></table></section>
    {creating && <div className="modal-backdrop" onMouseDown={() => setCreating(false)}><section className="reward-edit-modal" role="dialog" aria-modal="true" aria-labelledby="add-service-title" onMouseDown={event => event.stopPropagation()}><div className="privacy-modal-header"><div><p className="kicker">Catalog</p><h2 id="add-service-title">Add product or service</h2></div><button className="close-button" onClick={() => setCreating(false)} aria-label="Close">×</button></div><div className="reward-edit-body"><label><span>Name</span><input autoFocus value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} /></label><label><span>Description <small>Optional</small></span><textarea value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></label><label><span>Category</span><input value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value })} /></label><label className="toggle-row"><input type="checkbox" checked={draft.is_bookable} onChange={event => setDraft({ ...draft, is_bookable: event.target.checked })} /><span>Show in Schedule My Visit</span></label>{error && <p className="login-error">{error}</p>}</div><div className="privacy-modal-footer"><button className="admin-soft" onClick={() => setCreating(false)}>Cancel</button><button className="admin-primary" disabled={saving || !draft.name.trim()} onClick={add}>{saving ? "Adding…" : "Add to catalog"}</button></div></section></div>}
    {editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><section className="reward-edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-service-title" onMouseDown={event => event.stopPropagation()}><div className="privacy-modal-header"><div><p className="kicker">Products &amp; Services</p><h2 id="edit-service-title">Edit service</h2></div><button className="close-button" onClick={() => setEditing(null)} aria-label="Close">×</button></div><div className="reward-edit-body"><label><span>Service name</span><input value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><label><span>Description <small>Optional</small></span><textarea value={editing.description ?? ""} onChange={event => setEditing({ ...editing, description: event.target.value })} /></label><label><span>Category</span><input value={editing.category} onChange={event => setEditing({ ...editing, category: event.target.value })} /></label><label className="toggle-row"><input type="checkbox" checked={editing.is_bookable} onChange={event => setEditing({ ...editing, is_bookable: event.target.checked })} /><span>Show in Schedule My Visit</span></label><label className="toggle-row"><input type="checkbox" checked={editing.active} onChange={event => setEditing({ ...editing, active: event.target.checked })} /><span>Service is active</span></label>{error && <p className="login-error">{error}</p>}</div><div className="privacy-modal-footer"><button className="admin-soft" onClick={() => setEditing(null)}>Cancel</button><button className="admin-primary" disabled={saving || !editing.name.trim()} onClick={save}>{saving ? "Saving…" : "Save service"}</button></div></section></div>}
  </>;
}

function CustomersView({ data }: { data: AdminData }) {
  const [syncingGhl, setSyncingGhl] = useState(false); const [ghlMessage, setGhlMessage] = useState("");
  const [ghlLinks, setGhlLinks] = useState<Record<string, string>>({});
  const [contactDetails, setContactDetails] = useState<Record<string, string | null> | null>(null);
  useEffect(() => { const filter = (event: Event) => { const query = String((event as CustomEvent).detail ?? "").trim().toLowerCase(); document.querySelectorAll<HTMLTableRowElement>(".table-panel tbody tr").forEach(row => { row.hidden = Boolean(query) && !row.textContent?.toLowerCase().includes(query); }); }; window.addEventListener("admin:customer-search", filter); return () => window.removeEventListener("admin:customer-search", filter); }, []);
  async function syncGhlCustomers() { setSyncingGhl(true); setGhlMessage(""); const response = await fetch("/api/admin/ghl/sync-customers", { method: "POST" }); const result = await response.json(); const nextMessage = response.ok ? `${result.synced} new customer${result.synced === 1 ? "" : "s"} synced to GHL; ${result.skipped ?? 0} already synced and skipped; ${result.notInGhl ?? 0} not in GHL${result.failed ? `; ${result.failed} failed` : ""}.` : result.error ?? "Unable to sync customers."; setGhlMessage(nextMessage); window.alert(nextMessage); setSyncingGhl(false); }
  useEffect(() => { const tools = document.querySelector(".table-panel .table-tools"); if (!tools || tools.querySelector(".ghl-customer-sync")) return; const button = document.createElement("button"); button.className = "admin-soft ghl-customer-sync"; button.textContent = syncingGhl ? "Syncing..." : "Sync to GHL"; button.disabled = syncingGhl; button.onclick = syncGhlCustomers; tools.appendChild(button); return () => button.remove(); }, [syncingGhl]);
  useEffect(() => { const supabase = createClient(); supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) return; const { data: membership } = await supabase.from("staff_memberships").select("spa_id").eq("user_id", user.id).eq("active", true).maybeSingle(); if (!membership) return; const { data: profiles } = await supabase.from("profiles").select("id,ghl_contact_id,ghl_sync_status").eq("spa_id", membership.spa_id); setGhlLinks(Object.fromEntries((profiles ?? []).map(profile => [profile.id, profile.ghl_contact_id ? "synced" : profile.ghl_sync_status ?? "pending"]))); }); }, [syncingGhl]);
  useEffect(() => { document.querySelectorAll<HTMLTableRowElement>(".table-panel tbody tr").forEach((row, index) => { const customer = data.customers[index]; const cell = row.cells[4]; if (!customer || !cell) return; cell.querySelector(".ghl-sync-badge")?.remove(); const status = ghlLinks[customer.id] ?? "pending"; const badge = document.createElement("span"); badge.className = `ghl-sync-badge ${status}`; badge.textContent = status === "synced" ? "GHL synced" : status === "not_in_ghl" ? "Not in GHL" : status === "failed" ? "GHL error" : "GHL pending"; cell.appendChild(badge); }); }, [data.customers, ghlLinks]);
  const lastVisit = (userId: string) => (data.visits ?? []).filter(visit => visit.user_id === userId).sort((a, b) => +new Date(b.occurred_at) - +new Date(a.occurred_at))[0]?.occurred_at;
  const visitCount = (userId: string) => (data.visits ?? []).filter(visit => visit.user_id === userId).length;
  const [selected, setSelected] = useState<AdminCustomer | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [editingField, setEditingField] = useState<"visits" | "lastVisit" | null>(null); const [draftCount, setDraftCount] = useState(0); const [draftLastVisit, setDraftLastVisit] = useState("");
  useEffect(() => { if (!selected || editingField) { setContactDetails(null); return; } fetch(`/api/admin/customers/${selected.id}`).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setContactDetails(result.customer); }).catch(error => setMessage(error.message)); }, [selected, editingField]);
  useEffect(() => { const list = document.querySelector(".customer-detail-modal dl"); if (!list || !contactDetails) return; list.querySelectorAll(".loaded-contact-detail").forEach(item => item.remove()); const values: [string,string][] = [["Email", contactDetails.email || "Not provided"],["Phone", contactDetails.phone || "Not provided"],["Gender", contactDetails.gender || "Not provided"],["Address", [contactDetails.address_line_1,contactDetails.address_line_2,contactDetails.city,contactDetails.state,contactDetails.postal_code].filter(Boolean).join(", ") || "Not provided"],["GHL status", contactDetails.ghl_contact_id ? "GHL synced" : contactDetails.ghl_sync_status === "not_in_ghl" ? "Not in GHL" : contactDetails.ghl_sync_status || "Pending"]]; values.forEach(([label,value]) => { const row=document.createElement("div"); row.className="loaded-contact-detail"; const term=document.createElement("dt"); term.textContent=label; const description=document.createElement("dd"); description.textContent=value; row.append(term,description); list.appendChild(row); }); }, [contactDetails]);
  function openEditor(customer: AdminCustomer) { const last = lastVisit(customer.id); setSelected(customer); setDraftCount(visitCount(customer.id)); setDraftLastVisit(last ? new Date(last).toISOString().slice(0,16) : new Date().toISOString().slice(0,16)); setEditingField("visits"); setMessage(""); }
  async function adjust(method: "POST" | "DELETE") { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch(`/api/admin/customers/${selected.id}/visits`, { method }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "Unable to adjust visits."); setSaving(false); return; } setMessage(method === "POST" ? "Visit added successfully." : "Latest visit reversed successfully."); setTimeout(() => window.location.reload(), 700); }
  useEffect(() => { const table = document.querySelector(".table-panel table"); const edit = (event: Event) => { const cell = (event.target as HTMLElement).closest("td"); const row = cell?.closest("tr") as HTMLTableRowElement | null; if (!cell || !row || ![2,3].includes(cell.cellIndex)) return; const customer = data.customers[row.rowIndex - 1]; if (!customer) return; const last = lastVisit(customer.id); setSelected(customer); setDraftCount(visitCount(customer.id)); setDraftLastVisit(last ? new Date(last).toISOString().slice(0,16) : new Date().toISOString().slice(0,16)); setEditingField(cell.cellIndex === 2 ? "visits" : "lastVisit"); }; table?.addEventListener("dblclick", edit); return () => table?.removeEventListener("dblclick", edit); }, [data.customers, data.visits]);
  useEffect(() => { const table = document.querySelector(".table-panel table"); const open = (event: Event) => { const target = event.target as HTMLElement; const row = target.closest("tbody tr") as HTMLTableRowElement | null; if (!row) return; const customer = data.customers[row.rowIndex - 1]; if (!customer) return; if (target.closest(".customer-edit-button")) { event.preventDefault(); event.stopPropagation(); openEditor(customer); return; } setSelected(customer); setEditingField(null); setMessage(""); }; table?.addEventListener("click", open); return () => table?.removeEventListener("click", open); }, [data.customers, data.visits]);
  async function saveRecordEdit() { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch(`/api/admin/customers/${selected.id}/visits`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ visitCount: draftCount, lastVisitAt: draftCount > 0 ? new Date(draftLastVisit).toISOString() : null }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "Unable to update visit records."); setSaving(false); return; } setMessage("Visit records updated successfully."); setTimeout(() => window.location.reload(), 700); }
  if (selected && editingField) return <div className="modal-backdrop" onMouseDown={() => setEditingField(null)}><section className="customer-detail-modal" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}><button className="close-button" onClick={() => setEditingField(null)}>×</button><p className="kicker">Manual record correction</p><h2>{[selected.first_name, selected.last_name].filter(Boolean).join(" ")}</h2><p className="record-warning">Changes are saved as an administrator override and affect loyalty progress.</p><label className="record-edit-field"><span>Verified visits</span><input type="number" min="0" max="100" value={draftCount} onChange={event => setDraftCount(Number(event.target.value))} /></label><label className="record-edit-field"><span>Last visit</span><input type="datetime-local" disabled={draftCount === 0} value={draftLastVisit} onChange={event => setDraftLastVisit(event.target.value)} /></label>{message && <p className="login-error">{message}</p>}<div className="record-edit-actions"><button className="admin-soft" onClick={() => setEditingField(null)}>Cancel</button><button className="admin-primary" disabled={saving} onClick={saveRecordEdit}>{saving ? "Saving…" : "Save records"}</button></div></section></div>;
  return <><div className="admin-title"><div><p>Management</p><h1>Customers</h1><span>Use Edit to view customer details and manage verified visits.</span></div></div><section className="admin-panel table-panel"><div className="table-tools"><div><button className="active">All customers {data.customers.length}</button></div></div><table><thead><tr><th>Customer</th><th>Member code</th><th>Visits</th><th>Last visit</th><th>Status</th><th></th></tr></thead><tbody>{data.customers.map(customer => { const visit = lastVisit(customer.id); return <tr key={customer.id}><td><span className="service-mark">●</span><strong>{[customer.first_name, customer.last_name].filter(Boolean).join(" ")}</strong></td><td>{customer.member_code}</td><td><strong>{visitCount(customer.id)}</strong></td><td>{visit ? new Date(visit).toLocaleString() : "No visits yet"}</td><td><em className="active-status">● Active</em></td><td><button className="customer-edit-button" onClick={() => setSelected(customer)}>Edit</button></td></tr>; })}</tbody></table></section>{selected && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><section className="customer-detail-modal" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}>×</button><p className="kicker">Customer details</p><h2>{[selected.first_name, selected.last_name].filter(Boolean).join(" ")}</h2><dl><div><dt>Member code</dt><dd>{selected.member_code}</dd></div><div><dt>Verified visits</dt><dd>{visitCount(selected.id)}</dd></div><div><dt>Last visit</dt><dd>{lastVisit(selected.id) ? new Date(lastVisit(selected.id)!).toLocaleString() : "No visits yet"}</dd></div><div><dt>Joined</dt><dd>{new Date(selected.created_at).toLocaleString()}</dd></div></dl><div className="manual-visit-actions"><p><strong>Manual override</strong><small>Adjust only when correcting a verified check-in.</small></p><div><button disabled={saving || visitCount(selected.id) === 0} onClick={() => adjust("DELETE")}>− Reverse latest</button><button className="admin-primary" disabled={saving} onClick={() => adjust("POST")}>+ Add visit</button></div></div>{message && <p className={message.includes("success") ? "scanner-success" : "login-error"}>{message}</p>}</section></div>}</>;
}

function StaffManager() {
  type StaffRow = { id?: string; user_id: string; email: string; role: string; active: boolean; profile?: { first_name?: string; last_name?: string } | null };
  const [staff, setStaff] = useState<StaffRow[]>([]); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", password: "", role: "staff" });
  const load = () => fetch("/api/admin/staff").then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setStaff(result.staff ?? []); }).catch(error => setMessage(error.message));
  useEffect(() => { load(); }, []);
  async function addStaff() { setSaving(true); setMessage(""); const response = await fetch("/api/admin/staff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "Unable to add staff member."); setSaving(false); return; } setMessage("Staff member added and tagged as staff."); setForm({ firstName: "", lastName: "", email: "", password: "", role: "staff" }); setShowForm(false); await load(); setSaving(false); }
  return <><div className="admin-title"><div><p>Management</p><h1>Staff &amp; Access</h1><span>Team accounts are scoped to this spa and excluded from customers.</span></div><button className="admin-primary" onClick={() => setShowForm(true)}>+ Add staff member</button></div><section className="admin-panel table-panel"><div className="table-tools"><div><button className="active">All staff {staff.length}</button></div></div><table><thead><tr><th>Staff member</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{staff.map(item => <tr key={item.user_id}><td><strong>{[item.profile?.first_name, item.profile?.last_name].filter(Boolean).join(" ") || "Staff member"}</strong></td><td>{item.email}</td><td><span className="staff-role-badge">{item.role}</span></td><td><em className="active-status">{item.active ? "Active" : "Inactive"}</em></td></tr>)}</tbody></table>{!staff.length && <p className="empty-log staff-empty">No staff members have been added.</p>}</section>{message && <p className={message.includes("added") ? "scanner-success admin-toast" : "login-error admin-toast"}>{message}</p>}{showForm && <div className="modal-backdrop" onMouseDown={() => setShowForm(false)}><section className="staff-create-modal" onMouseDown={event => event.stopPropagation()}><button className="close-button" onClick={() => setShowForm(false)}>×</button><p className="kicker">Spa team</p><h2>Add staff member</h2><div className="staff-form-grid"><label><span>First name</span><input value={form.firstName} onChange={event => setForm({ ...form, firstName: event.target.value })} /></label><label><span>Last name</span><input value={form.lastName} onChange={event => setForm({ ...form, lastName: event.target.value })} /></label><label className="form-wide"><span>Email</span><input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label><span>Temporary password</span><input type="password" minLength={8} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label><span>Role</span><select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label></div>{message && !message.includes("added") && <p className="login-error">{message}</p>}<div className="record-edit-actions"><button className="admin-soft" onClick={() => setShowForm(false)}>Cancel</button><button className="admin-primary" disabled={saving || !form.email || form.password.length < 8} onClick={addStaff}>{saving ? "Adding..." : "Add staff member"}</button></div></section></div>}</>;
}

function DataView({ view, data, onRewardUpdated, onServiceUpdated, onServiceCreated, onServiceDeleted }: { view: Exclude<AdminView, "overview" | "calendar" | "activity" | "settings">; data: AdminData; onRewardUpdated: (reward: AdminReward) => void; onServiceUpdated: (service: AdminService) => void; onServiceCreated: (service: AdminService) => void; onServiceDeleted: (id: string) => void }) {
  const titles = { customers: ["Customers", "Manage customer profiles and spa-linked memberships."], loyalty: ["Loyalty & Offers", "Configure visit milestones and rewards for Spa 1."], services: ["Products & Services", "Manage bookable services and reward products."], staff: ["Staff", "Control team access and roles for this spa."] } as const;
  const [title, description] = titles[view];
  if ((view as AdminView) === "customers") return <CustomersView data={data} />;
  if (view === "loyalty") return <LoyaltyEditor rewards={data.rewards} onUpdated={onRewardUpdated} />;
  if (view === "services") return <ServicesEditor services={data.services} onUpdated={onServiceUpdated} onCreated={onServiceCreated} onDeleted={onServiceDeleted} />;
  if (view === "staff") return <StaffManager />;
  if (view === "customers") return <><div className="admin-title"><div><p>Management</p><h1>{title}</h1><span>{description}</span></div><button className="admin-primary">+ Add customer</button></div><section className="admin-panel table-panel"><div className="table-tools"><div><button className="active">All customers {data.customers.length}</button></div></div><table><thead><tr><th>Customer</th><th>Member code</th><th>Joined</th><th>Status</th><th></th></tr></thead><tbody>{data.customers.map(customer => <tr key={customer.id}><td><span className="service-mark">●</span><strong>{[customer.first_name, customer.last_name].filter(Boolean).join(" ")}</strong></td><td>{customer.member_code}</td><td>{new Date(customer.created_at).toLocaleDateString()}</td><td><em className="active-status">● Active</em></td><td><button>•••</button></td></tr>)}</tbody></table></section></>;
  return <><div className="admin-title"><div><p>Management</p><h1>{title}</h1><span>{description}</span></div><button className="admin-primary">+ Add {view === "staff" ? "staff member" : "offer"}</button></div><section className="admin-panel empty-admin"><span>{nav.find(item => item.id === view)?.icon}</span><h2>{title} workspace</h2><p>This module is ready for live Supabase data and admin workflows.</p><button className="admin-soft">Configure {title.toLowerCase()}</button></section></>;
}

function GeneralSettings() {
  return <><div className="admin-title"><div><p>Configuration</p><h1>Spa Settings</h1><span>Manage the spa’s identity and contact information.</span></div><span className="sample-badge large">Active spa</span></div><section className="admin-panel settings-panel"><div className="settings-heading"><span>01</span><div><h2>General information</h2><p>This information identifies the spa throughout the platform.</p></div></div><form onSubmit={event => event.preventDefault()}><label><span>Spa name</span><input defaultValue="Prime IV Hydration & Wellness" /></label><label><span>Portal slug</span><div className="input-prefix"><b>/spa/</b><input defaultValue="spa-1" /></div></label><label><span>Support email</span><input type="email" placeholder="support@example.com" /></label><label><span>Support phone</span><input type="tel" placeholder="(555) 000-0000" /></label><div className="form-wide tenant-id"><span>Spa ID</span><code>485a0da3-0c95-489c-894b-c84f61f7cefa</code><small>Permanent spa database identifier</small></div><div className="settings-actions"><button className="admin-soft" type="reset">Cancel</button><button className="admin-primary" type="submit">Save changes</button></div></form></section></>;
}

function GhlSettings() {
  const [locationId, setLocationId] = useState(""); const [pitKey, setPitKey] = useState(""); const [enabled, setEnabled] = useState(true); const [hasKey, setHasKey] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [syncSuccess, setSyncSuccess] = useState(false);
  useEffect(() => { fetch("/api/admin/ghl").then(response => response.json()).then(result => { if (result.connection) { setLocationId(result.connection.location_id); setEnabled(result.connection.enabled); setHasKey(result.connection.hasPitKey); if (result.connection.last_sync_status === "success") { setSyncSuccess(true); setMessage(`Connected and saved custom fields — Spa_Visits: ${result.connection.spa_visits_field_id} · Last_Spa_Visits: ${result.connection.last_spa_visits_field_id}`); } } }).catch(() => {}); }, []);
  async function save() { setSaving(true); setMessage(""); setSyncSuccess(false); const response = await fetch("/api/admin/ghl", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ locationId, pitKey, enabled }) }); const result = await response.json(); if (!response.ok) setMessage(result.error ?? "Unable to sync GHL settings."); else { setMessage(`Sync successful and saved — Spa_Visits field ID: ${result.fieldIds.spaVisits} · Last_Spa_Visits field ID: ${result.fieldIds.lastSpaVisits}`); setSyncSuccess(true); setPitKey(""); setHasKey(true); } setSaving(false); }
  return <section className="admin-panel ghl-settings"><div className="settings-heading"><span>GHL</span><div><h2>Sync to GoHighLevel</h2><p>Connect this spa to its own GoHighLevel location.</p></div></div><div className="ghl-form"><label><span>Location ID</span><input value={locationId} onChange={event => setLocationId(event.target.value)} placeholder="Enter GHL Location ID" /></label><label><span>Location PIT key</span><input type="password" value={pitKey} onChange={event => setPitKey(event.target.value)} placeholder={hasKey ? "Saved securely — enter a new key to replace" : "Enter private integration token"} autoComplete="new-password" /></label><label className="toggle-row"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} /><span>Enable GHL sync for this spa</span></label><div className="ghl-security-note">The PIT key is encrypted before storage and is never shown again.</div>{message && <p className={message.includes("saved") ? "scanner-success" : "login-error"}>{message}</p>}<div className="settings-actions"><button className="admin-primary" disabled={saving || !locationId.trim() || (!hasKey && !pitKey.trim())} onClick={save}>{saving ? "Saving…" : "Save GHL connection"}</button></div></div></section>;
}

function Settings() {
  const open = (view: AdminView) => window.dispatchEvent(new CustomEvent("admin:navigate", { detail: view }));
  return <div className="settings-page"><div className="admin-title"><div><p>Configuration</p><h1>Spa Settings</h1><span>Manage your spa, integrations, loyalty program, catalog, and staff access.</span></div><span className="sample-badge large">Sample spa</span></div><div className="settings-module-grid"><button onClick={() => open("loyalty")}><span>◇</span><div><strong>Loyalty &amp; Offers</strong><small>Configure visit milestones and rewards</small></div><b>→</b></button><button onClick={() => open("services")}><span>◉</span><div><strong>Products &amp; Services</strong><small>Manage scheduling options and reward products</small></div><b>→</b></button><button onClick={() => open("staff")}><span>♧</span><div><strong>Staff &amp; Access</strong><small>Manage team members and permissions</small></div><b>→</b></button></div><div className="settings-columns"><GeneralSettings /><GhlSettings /></div></div>;
}

function CalendarView({ appointments: allAppointments, customers }: { appointments: AdminAppointment[]; customers: AdminCustomer[] }) {
  const appointments = allAppointments.filter(item => ["requested", "confirmed"].includes(item.status));
  const [cursor, setCursor] = useState(() => new Date());
  const year = cursor.getFullYear(); const month = cursor.getMonth();
  const first = new Date(year, month, 1); const days = new Date(year, month + 1, 0).getDate();
  const cells = Array.from({ length: first.getDay() + days }, (_, index) => index < first.getDay() ? null : index - first.getDay() + 1);
  const customerName = (id: string) => { const customer = customers.find(item => item.id === id); return customer ? [customer.first_name, customer.last_name].filter(Boolean).join(" ") : "Customer"; };
  return <><div className="admin-title"><div><p>Scheduling</p><h1>Appointment Calendar</h1><span>Monthly view of this spa&apos;s appointments.</span></div><div className="calendar-controls"><button onClick={() => setCursor(new Date(year, month - 1, 1))}>←</button><strong>{cursor.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</strong><button onClick={() => setCursor(new Date(year, month + 1, 1))}>→</button></div></div><section className="admin-panel calendar-panel"><div className="calendar-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day => <b key={day}>{day}</b>)}</div><div className="calendar-grid">{cells.map((day, index) => <div className={!day ? "calendar-day empty" : "calendar-day"} key={index}>{day && <><span>{day}</span>{appointments.filter(item => { const date = new Date(item.scheduled_start); return date.getFullYear() === year && date.getMonth() === month && date.getDate() === day; }).map(item => <article key={item.id}><time>{new Date(item.scheduled_start).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time><strong>{item.service_name}</strong><small>{customerName(item.user_id)}</small></article>)}</>}</div>)}</div></section></>;
}

function AdminActivityView({ data }: { data: AdminData }) {
  const customerName = (userId?: string) => { const customer = data.customers.find(item => item.id === userId); return customer ? [customer.first_name, customer.last_name].filter(Boolean).join(" ") || customer.member_code : "Customer"; };
  const rows = [...(data.visits ?? []).map(item => ({ id: `visit-${item.id}`, title: "Successful QR check-in", detail: `${customerName(item.user_id)} · Verified loyalty visit recorded`, at: item.occurred_at })), ...data.appointments.map(item => ({ id: `appointment-${item.id}`, title: `${item.service_name} self-booking`, detail: `${customerName(item.user_id)} · ${item.status === "requested" ? "Self-booked" : item.status}`, at: item.scheduled_start })), ...data.customers.map(item => ({ id: `customer-${item.id}`, title: "Customer registered", detail: [item.first_name, item.last_name].filter(Boolean).join(" ") || item.member_code, at: item.created_at }))].sort((a, b) => +new Date(b.at) - +new Date(a.at));
  return <><div className="admin-title"><div><p>Monitoring</p><h1>Activity Logs</h1><span>Latest customer and appointment activity for this spa.</span></div></div><section className="admin-panel admin-activity-page">{rows.length ? rows.map(item => <article key={item.id}><span /><div><strong>{item.title}</strong><small>{item.detail}</small></div><time>{new Date(item.at).toLocaleString()}</time></article>) : <p className="empty-log">No activity yet.</p>}</section></>;
}

export default function AdminPage() {
  const router = useRouter();
  const [view, setView] = useState<AdminView>("overview");
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<AdminData>({ customers: [], services: [], rewards: [], appointments: [], visits: [], loyaltyMembers: 0, rewardsIssued: 0 });
  const title = ({ overview: "Overview", customers: "Customers", calendar: "Calendar", activity: "Logs", settings: "Spa Settings", loyalty: "Loyalty & Offers", services: "Products & Services", staff: "Staff & Access" } as Record<AdminView, string>)[view];
  useEffect(() => { const navigate = (event: Event) => setView((event as CustomEvent<AdminView>).detail); window.addEventListener("admin:navigate", navigate); return () => window.removeEventListener("admin:navigate", navigate); }, []);
  useEffect(() => { const supabase = createClient(); (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace("/login"); return; } const { data: staff } = await supabase.from("staff_memberships").select("role,spa_id").eq("user_id", user.id).eq("active", true).maybeSingle(); if (!staff) { router.replace("/"); return; } const [customersResult, staffResult, servicesResult, definitionsResult, appointmentsResult, accountsResult, rewardsResult] = await Promise.all([supabase.from("profiles").select("id,first_name,last_name,member_code,created_at").eq("spa_id", staff.spa_id).order("created_at", { ascending: false }), supabase.from("staff_memberships").select("user_id").eq("spa_id", staff.spa_id).eq("active", true), supabase.from("services").select("id,name,description,category,is_bookable,active,display_order").eq("spa_id", staff.spa_id).order("display_order"), supabase.from("reward_definitions").select("id,visit_number,name,description,terms,valid_days,is_free_product,active").eq("spa_id", staff.spa_id).order("visit_number"), supabase.from("appointments").select("id,user_id,service_name,scheduled_start,status").eq("spa_id", staff.spa_id).order("scheduled_start"), supabase.from("loyalty_accounts").select("id", { count: "exact", head: true }).eq("spa_id", staff.spa_id).eq("active", true), supabase.from("reward_awards").select("id", { count: "exact", head: true }).eq("spa_id", staff.spa_id)]); const staffIds = new Set((staffResult.data ?? []).map(item => item.user_id)); setData({ customers: (customersResult.data ?? []).filter(customer => !staffIds.has(customer.id)), services: servicesResult.data ?? [], rewards: definitionsResult.data ?? [], appointments: appointmentsResult.data ?? [], loyaltyMembers: accountsResult.count ?? 0, rewardsIssued: rewardsResult.count ?? 0 }); setLoading(false); })(); }, [router]);
  useEffect(() => { const supabase = createClient(); (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: staff } = await supabase.from("staff_memberships").select("spa_id").eq("user_id", user.id).eq("active", true).maybeSingle(); if (!staff) return; const [{ data: accounts }, { data: visits }] = await Promise.all([supabase.from("loyalty_accounts").select("id,user_id").eq("spa_id", staff.spa_id), supabase.from("visit_events").select("id,account_id,occurred_at").eq("spa_id", staff.spa_id).is("reversed_at", null).order("occurred_at", { ascending: false })]); const users = new Map((accounts ?? []).map(account => [account.id, account.user_id])); setData(current => ({ ...current, visits: (visits ?? []).map(visit => ({ ...visit, user_id: users.get(visit.account_id) ?? "" })) })); })(); }, []);
  useEffect(() => { const supabase = createClient(); let spaId = ""; let active = true; const refresh = async () => { if (!spaId) { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: staff } = await supabase.from("staff_memberships").select("spa_id").eq("user_id", user.id).eq("active", true).maybeSingle(); spaId = staff?.spa_id ?? ""; } if (!spaId) return; const [{ data: accounts }, { data: visits }, { data: appointments }] = await Promise.all([supabase.from("loyalty_accounts").select("id,user_id").eq("spa_id", spaId), supabase.from("visit_events").select("id,account_id,occurred_at").eq("spa_id", spaId).is("reversed_at", null).order("occurred_at", { ascending: false }), supabase.from("appointments").select("id,user_id,service_name,scheduled_start,status").eq("spa_id", spaId).order("scheduled_start")]); if (!active) return; const users = new Map((accounts ?? []).map(account => [account.id, account.user_id])); setData(current => ({ ...current, visits: (visits ?? []).map(visit => ({ ...visit, user_id: users.get(visit.account_id) ?? "" })), appointments: appointments ?? [] })); }; const timer = setInterval(refresh, 4000); return () => { active = false; clearInterval(timer); }; }, []);
  if (loading) return <main className="portal-loading"><p>Loading admin workspace…</p></main>;
  return <main className="admin-layout"><AdminSidebar view={view} setView={setView} /><div className="admin-main"><AdminHeader title={title} /><div className="admin-content">{view === "overview" ? <Overview data={data} openCustomers={() => setView("customers")} /> : view === "calendar" ? <CalendarView appointments={data.appointments} customers={data.customers} /> : view === "activity" ? <AdminActivityView data={data} /> : view === "settings" ? <Settings /> : <DataView view={view} data={data} onRewardUpdated={reward => setData(current => ({ ...current, rewards: current.rewards.map(item => item.id === reward.id ? reward : item) }))} onServiceUpdated={service => setData(current => ({ ...current, services: current.services.map(item => item.id === service.id ? service : item) }))} onServiceCreated={service => setData(current => ({ ...current, services: [...current.services, service] }))} onServiceDeleted={id => setData(current => ({ ...current, services: current.services.filter(item => item.id !== id) }))} />}</div></div><div className="admin-mobile-block"><Image src="/prime-iv-logo.png" alt="Prime IV" width={150} height={120} /><h1>Admin portal requires a desktop</h1><p>Open this workspace on a screen at least 1024 pixels wide.</p><Link href="/">Return to customer portal</Link></div></main>;
}
